INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Andorra', 'Andorra la Vella', '84000', '468.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'United Arab Emirates', 'Abu Dhabi', '4975593', '82880.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Afghanistan', 'Kabul', '29121286', '647500.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Antigua and Barbuda', 'St. John's', '86754', '443.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Anguilla', 'The Valley', '13254', '102.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Albania', 'Tirana', '2986952', '28748.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Armenia', 'Yerevan', '2968000', '29800.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Angola', 'Luanda', '13068161', '1246700.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Antarctica', 'None', '0', '1.4E7' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Argentina', 'Buenos Aires', '41343201', '2766890.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'American Samoa', 'Pago Pago', '57881', '199.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Austria', 'Vienna', '8205000', '83858.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Australia', 'Canberra', '21515754', '7686850.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Aruba', 'Oranjestad', '71566', '193.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Åland', 'Mariehamn', '26711', '1580.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Azerbaijan', 'Baku', '8303512', '86600.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Bosnia and Herzegovina', 'Sarajevo', '4590000', '51129.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Barbados', 'Bridgetown', '285653', '431.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Bangladesh', 'Dhaka', '156118464', '144000.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Belgium', 'Brussels', '10403000', '30510.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Burkina Faso', 'Ouagadougou', '16241811', '274200.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Bulgaria', 'Sofia', '7148785', '110910.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Bahrain', 'Manama', '738004', '665.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Burundi', 'Bujumbura', '9863117', '27830.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Benin', 'Porto-Novo', '9056010', '112620.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Saint Barthélemy', 'Gustavia', '8450', '21.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Bermuda', 'Hamilton', '65365', '53.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Brunei', 'Bandar Seri Begawan', '395027', '5770.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Bolivia', 'Sucre', '9947418', '1098580.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Bonaire', 'Kralendijk', '18012', '328.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Brazil', 'Brasília', '201103330', '8511965.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Bahamas', 'Nassau', '301790', '13940.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Bhutan', 'Thimphu', '699847', '47000.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Bouvet Island', 'None', '0', '49.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Botswana', 'Gaborone', '2029307', '600370.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Belarus', 'Minsk', '9685000', '207600.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Belize', 'Belmopan', '314522', '22966.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Canada', 'Ottawa', '33679000', '9984670.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Cocos [Keeling] Islands', 'West Island', '628', '14.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Democratic Republic of the Congo', 'Kinshasa', '70916439', '2345410.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Central African Republic', 'Bangui', '4844927', '622984.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Republic of the Congo', 'Brazzaville', '3039126', '342000.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Switzerland', 'Bern', '7581000', '41290.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Ivory Coast', 'Yamoussoukro', '21058798', '322460.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Cook Islands', 'Avarua', '21388', '240.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Chile', 'Santiago', '16746491', '756950.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Cameroon', 'Yaoundé', '19294149', '475440.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'China', 'Beijing', '1330044000', '9596960.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Colombia', 'Bogotá', '47790000', '1138910.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Costa Rica', 'San José', '4516220', '51100.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Cuba', 'Havana', '11423000', '110860.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Cape Verde', 'Praia', '508659', '4033.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Curacao', 'Willemstad', '141766', '444.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Christmas Island', 'Flying Fish Cove', '1500', '135.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Cyprus', 'Nicosia', '1102677', '9250.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Czech Republic', 'Prague', '10476000', '78866.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Germany', 'Berlin', '81802257', '357021.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Djibouti', 'Djibouti', '740528', '23000.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Denmark', 'Copenhagen', '5484000', '43094.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Dominica', 'Roseau', '72813', '754.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Dominican Republic', 'Santo Domingo', '9823821', '48730.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Algeria', 'Algiers', '34586184', '2381740.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Ecuador', 'Quito', '14790608', '283560.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Estonia', 'Tallinn', '1291170', '45226.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Egypt', 'Cairo', '80471869', '1001450.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Western Sahara', 'Laâyoune / El Aaiún', '273008', '266000.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Eritrea', 'Asmara', '5792984', '121320.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Spain', 'Madrid', '46505963', '504782.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Ethiopia', 'Addis Ababa', '88013491', '1127127.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Finland', 'Helsinki', '5244000', '337030.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Fiji', 'Suva', '875983', '18270.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Falkland Islands', 'Stanley', '2638', '12173.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Micronesia', 'Palikir', '107708', '702.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Faroe Islands', 'Tórshavn', '48228', '1399.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'France', 'Paris', '64768389', '547030.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Gabon', 'Libreville', '1545255', '267667.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'United Kingdom', 'London', '62348447', '244820.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Grenada', 'St. George's', '107818', '344.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Georgia', 'Tbilisi', '4630000', '69700.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'French Guiana', 'Cayenne', '195506', '91000.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Guernsey', 'St Peter Port', '65228', '78.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Ghana', 'Accra', '24339838', '239460.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Gibraltar', 'Gibraltar', '27884', '6.5' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Greenland', 'Nuuk', '56375', '2166086.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Gambia', 'Bathurst', '1593256', '11300.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Guinea', 'Conakry', '10324025', '245857.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Guadeloupe', 'Basse-Terre', '443000', '1780.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Equatorial Guinea', 'Malabo', '1014999', '28051.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Greece', 'Athens', '11000000', '131940.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'South Georgia and the South Sandwich Islands', 'Grytviken', '30', '3903.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Guatemala', 'Guatemala City', '13550440', '108890.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Guam', 'Hagåtña', '159358', '549.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Guinea-Bissau', 'Bissau', '1565126', '36120.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Guyana', 'Georgetown', '748486', '214970.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Hong Kong', 'Hong Kong', '6898686', '1092.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Heard Island and McDonald Islands', 'None', '0', '412.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Honduras', 'Tegucigalpa', '7989415', '112090.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Croatia', 'Zagreb', '4491000', '56542.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Haiti', 'Port-au-Prince', '9648924', '27750.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Hungary', 'Budapest', '9982000', '93030.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Indonesia', 'Jakarta', '242968342', '1919440.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Ireland', 'Dublin', '4622917', '70280.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Israel', 'None', '7353985', '20770.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Isle of Man', 'Douglas', '75049', '572.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'India', 'New Delhi', '1173108018', '3287590.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'British Indian Ocean Territory', 'None', '4000', '60.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Iraq', 'Baghdad', '29671605', '437072.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Iran', 'Tehran', '76923300', '1648000.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Iceland', 'Reykjavik', '308910', '103000.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Italy', 'Rome', '60340328', '301230.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Jersey', 'Saint Helier', '90812', '116.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Jamaica', 'Kingston', '2847232', '10991.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Jordan', 'Amman', '6407085', '92300.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Japan', 'Tokyo', '127288000', '377835.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Kenya', 'Nairobi', '40046566', '582650.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Kyrgyzstan', 'Bishkek', '5776500', '198500.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Cambodia', 'Phnom Penh', '14453680', '181040.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Kiribati', 'Tarawa', '92533', '811.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Comoros', 'Moroni', '773407', '2170.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Saint Kitts and Nevis', 'Basseterre', '51134', '261.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'North Korea', 'Pyongyang', '22912177', '120540.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'South Korea', 'Seoul', '48422644', '98480.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Kuwait', 'Kuwait City', '2789132', '17820.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Cayman Islands', 'George Town', '44270', '262.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Kazakhstan', 'Astana', '15340000', '2717300.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Laos', 'Vientiane', '6368162', '236800.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Lebanon', 'Beirut', '4125247', '10400.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Saint Lucia', 'Castries', '160922', '616.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Liechtenstein', 'Vaduz', '35000', '160.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Sri Lanka', 'Colombo', '21513990', '65610.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Liberia', 'Monrovia', '3685076', '111370.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Lesotho', 'Maseru', '1919552', '30355.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Lithuania', 'Vilnius', '2944459', '65200.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Luxembourg', 'Luxembourg', '497538', '2586.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Latvia', 'Riga', '2217969', '64589.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Libya', 'Tripoli', '6461454', '1759540.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Morocco', 'Rabat', '31627428', '446550.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Monaco', 'Monaco', '32965', '1.95' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Moldova', 'Chişinău', '4324000', '33843.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Montenegro', 'Podgorica', '666730', '14026.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Saint Martin', 'Marigot', '35925', '53.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Madagascar', 'Antananarivo', '21281844', '587040.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Marshall Islands', 'Majuro', '65859', '181.3' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Macedonia', 'Skopje', '2062294', '25333.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Mali', 'Bamako', '13796354', '1240000.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Myanmar [Burma]', 'Naypyitaw', '53414374', '678500.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Mongolia', 'Ulan Bator', '3086918', '1565000.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Macao', 'Macao', '449198', '254.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Northern Mariana Islands', 'Saipan', '53883', '477.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Martinique', 'Fort-de-France', '432900', '1100.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Mauritania', 'Nouakchott', '3205060', '1030700.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Montserrat', 'Plymouth', '9341', '102.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Malta', 'Valletta', '403000', '316.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Mauritius', 'Port Louis', '1294104', '2040.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Maldives', 'Malé', '395650', '300.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Malawi', 'Lilongwe', '15447500', '118480.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Mexico', 'Mexico City', '112468855', '1972550.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Malaysia', 'Kuala Lumpur', '28274729', '329750.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Mozambique', 'Maputo', '22061451', '801590.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Namibia', 'Windhoek', '2128471', '825418.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'New Caledonia', 'Noumea', '216494', '19060.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Niger', 'Niamey', '15878271', '1267000.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Norfolk Island', 'Kingston', '1828', '34.6' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Nigeria', 'Abuja', '154000000', '923768.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Nicaragua', 'Managua', '5995928', '129494.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Netherlands', 'Amsterdam', '16645000', '41526.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Norway', 'Oslo', '5009150', '324220.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Nepal', 'Kathmandu', '28951852', '140800.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Nauru', 'Yaren', '10065', '21.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Niue', 'Alofi', '2166', '260.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'New Zealand', 'Wellington', '4252277', '268680.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Oman', 'Muscat', '2967717', '212460.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Panama', 'Panama City', '3410676', '78200.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Peru', 'Lima', '29907003', '1285220.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'French Polynesia', 'Papeete', '270485', '4167.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Papua New Guinea', 'Port Moresby', '6064515', '462840.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Philippines', 'Manila', '99900177', '300000.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Pakistan', 'Islamabad', '184404791', '803940.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Poland', 'Warsaw', '38500000', '312685.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Saint Pierre and Miquelon', 'Saint-Pierre', '7012', '242.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Pitcairn Islands', 'Adamstown', '46', '47.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Puerto Rico', 'San Juan', '3916632', '9104.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Palestine', 'None', '3800000', '5970.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Portugal', 'Lisbon', '10676000', '92391.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Palau', 'Melekeok', '19907', '458.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Paraguay', 'Asunción', '6375830', '406750.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Qatar', 'Doha', '840926', '11437.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Réunion', 'Saint-Denis', '776948', '2517.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Romania', 'Bucharest', '21959278', '237500.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Serbia', 'Belgrade', '7344847', '88361.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Russia', 'Moscow', '140702000', '1.71E7' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Rwanda', 'Kigali', '11055976', '26338.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Saudi Arabia', 'Riyadh', '25731776', '1960582.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Solomon Islands', 'Honiara', '559198', '28450.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Seychelles', 'Victoria', '88340', '455.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Sudan', 'Khartoum', '35000000', '1861484.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Sweden', 'Stockholm', '9828655', '449964.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Singapore', 'Singapore', '4701069', '692.7' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Saint Helena', 'Jamestown', '7460', '410.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Slovenia', 'Ljubljana', '2007000', '20273.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Svalbard and Jan Mayen', 'Longyearbyen', '2550', '62049.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Slovakia', 'Bratislava', '5455000', '48845.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Sierra Leone', 'Freetown', '5245695', '71740.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'San Marino', 'San Marino', '31477', '61.2' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Senegal', 'Dakar', '12323252', '196190.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Somalia', 'Mogadishu', '10112453', '637657.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Suriname', 'Paramaribo', '492829', '163270.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'South Sudan', 'Juba', '8260490', '644329.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'São Tomé and Príncipe', 'São Tomé', '175808', '1001.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'El Salvador', 'San Salvador', '6052064', '21040.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Sint Maarten', 'Philipsburg', '37429', '21.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Syria', 'Damascus', '22198110', '185180.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Swaziland', 'Mbabane', '1354051', '17363.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Turks and Caicos Islands', 'Cockburn Town', '20556', '430.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Chad', 'N'Djamena', '10543464', '1284000.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'French Southern Territories', 'Port-aux-Français', '140', '7829.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Togo', 'Lomé', '6587239', '56785.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Thailand', 'Bangkok', '67089500', '514000.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Tajikistan', 'Dushanbe', '7487489', '143100.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Tokelau', 'None', '1466', '10.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'East Timor', 'Dili', '1154625', '15007.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Turkmenistan', 'Ashgabat', '4940916', '488100.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Tunisia', 'Tunis', '10589025', '163610.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Tonga', 'Nuku'alofa', '122580', '748.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Turkey', 'Ankara', '77804122', '780580.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Trinidad and Tobago', 'Port of Spain', '1228691', '5128.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Tuvalu', 'Funafuti', '10472', '26.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Taiwan', 'Taipei', '22894384', '35980.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Tanzania', 'Dodoma', '41892895', '945087.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Ukraine', 'Kiev', '45415596', '603700.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Uganda', 'Kampala', '33398682', '236040.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'U.S. Minor Outlying Islands', 'None', '0', '0.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'United States', 'Washington', '310232863', '9629091.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Uruguay', 'Montevideo', '3477000', '176220.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Uzbekistan', 'Tashkent', '27865738', '447400.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Vatican City', 'Vatican City', '921', '0.44' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Saint Vincent and the Grenadines', 'Kingstown', '104217', '389.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Venezuela', 'Caracas', '27223228', '912050.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'British Virgin Islands', 'Road Town', '21730', '153.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'U.S. Virgin Islands', 'Charlotte Amalie', '108708', '352.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Vietnam', 'Hanoi', '89571130', '329560.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Vanuatu', 'Port Vila', '221552', '12200.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Wallis and Futuna', 'Mata-Utu', '16025', '274.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Samoa', 'Apia', '192001', '2944.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Kosovo', 'Pristina', '1800000', '10908.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Yemen', 'Sanaa', '23495361', '527970.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Mayotte', 'Mamoudzou', '159042', '374.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'South Africa', 'Pretoria', '49000000', '1219912.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Zambia', 'Lusaka', '13460305', '752614.0' );
INSERT INTO mytable ( country_name, country_capital, country_population, country_area ) VALUES ( 'Zimbabwe', 'Harare', '11651858', '390580.0' );
